### PR TITLE
Fix for new structure from Google Scholar

### PR DESCRIPTION
**Pull request by OleAd**
Fixed to match current returns from Google Scholar. Script works and passes test.py as of March 20th 2019.

### CODE REVIEW

**Comment by joausaga** [comment]
We need to merge this into master. Currently, the search author function is broken

**Comment by ipeirotis** [comment]
Can we start getting the pull requests merged into the base branch?

**Comment by cjekel** [comment]
@OleAd 
1. Can you revert https://github.com/OrganicIrradiation/scholarly/pull/30/commits/9eb8d0659c7d3db3131623cdcff87eca30b6a053 , or change the PR to a branch which doesn't have this commit.
2. Can you roll the minor version in setup.py
3. The test is not working. There are now 58 authors. Perhaps we should make this test ```assertTrue(len(authors) >=  57)```

Then we can ping Steven for a PyPI release.

--- 
This PR would close https://github.com/OrganicIrradiation/scholarly/issues/27

**Comment by OleAd** [comment]
@cjekel Will take a look at it, but no guarantee on time frame. Agree with the test case, which should be changed for all the other tests as well.

**Comment by OrganicIrradiation** [comment]
I believe everything should be fixed and have updated the PyPi version. Could you please confirm?

**Comment by cjekel** [comment]
@OrganicIrradiation 
```scholarly==0.2.5``` on PyPi appears to have fixed this issue for me

**Pull request closed without merging**
