### PR TITLE
Revised test suite, fixed issues raised by flake8, made network calls more persistent

### PR DESCRIPTION
**Pull request by ipeirotis**
I found it hard to get the test suite to run even with the free proxies.

I revised the network call function to be more persistent. 

The test suite uses Tor if it runs, otherwise uses proxies.

### CODE REVIEW

**Comment by ipeirotis** [comment]
Thanks for pointing to your code. I added the additional checks for the "captcha-style" issues. (Btw, your branch codebase is _so_ much better. Looking forward to moving the current code to that.)

Tests are still not super stable, and especially the `get_cited_by` test tends to fail often.

As we fix some of the outstanding issues, I will try to add a corresponding test for each bug.

We need also to figure out how to publish the current code into PyPI. I added issue https://github.com/OrganicIrradiation/scholarly/issues/90 to keep track of that.

Your point about windows is also valid. I added issue https://github.com/OrganicIrradiation/scholarly/issues/89 so that we can move the current Github actions to also build on windows and mac. Need to figure out how to install and use Tor as part of the build process for these platforms.

**Comment by silvavn** [comment]
No problem! When you port code, please remember to add the github handle of the author to your commit so they also get credit for their contribution! :)

One thing that I would say is essential right now would be adding the random user_agent, that will make the agent to fail less often and be less detectable. That is also part of my fork. Another thing is to put each class into their own file, since code is becoming too big for a single scholarly.py

I believe [stem can launch a tor instance](https://stem.torproject.org/tutorials/to_russia_with_love.html), but its a linux only thing.

Good work!

**Comment by bielsnohr** [comment]
Great work! My only concern is that now Tor/proxies are no longer optional and have become central features of the code. So, either the README needs to be updated to state as such, or we need to redesign.

**Comment by ipeirotis** [comment]
They are still optional, as the code will still work without Tor running. 

Nevertheless, we should make the choice of using Tor/proxies/whatever a central part of the code.

Ideally, we would like Tor to run silently as part of scholarly, instead of requiring a separate installation. I checked `torpy` (https://pypi.org/project/torpy/) which runs a Tor client directly in Python (i.e., no need for a separate Tor installation) but it was not stable. Run better than using FreeProxies, but worse than interacting with the official Tor client through `stem`

**Comment by bielsnohr** [comment]
Ah, I misread the code. Didn't see that `_PROXIES` defaults to `None` unless it is explicitly set. I was worried the README was out of date as a result. Perhaps we should say that Tor will automatically be used if it is running and if scholarly detects it?

**Comment by ipeirotis** [comment]
Not a bad idea to add a note in the README about the autodetection of Tor, and the extra benefit of setting a controller.

Ultimately though it seems that `stem` can run directly a Tor client and we can use tor without having to be explicit about that. 

I added the ticket https://github.com/OrganicIrradiation/scholarly/issues/94 to keep track of this feature request.

**Pull request merged**
