### PR TITLE
Documentation, Extended support, code improvement

### PR DESCRIPTION
**Pull request by silvavn**
1. Documented the code using sphinx
2. Separated Scholarly, Publication and Author into different files
3. Added search_single_pub to Scholarly
4. Fixed bibtex collection and handled exceptions
5. Expanded support to Chrome and Firefox Webdrivers
6. Randomized Selenium features for both drivers.
7. Implemented a no-wait policy when using ToR, for faster study collection.
8. Implemented expanded error handling for traffic, automation and captchas,
9. Moved hardcoding to a json file for improved code maintenance

### CODE REVIEW

**Comment by janruh** [comment]
This seems to be the most recent fork that would make sense to merge.

**Comment by silvavn** [comment]
@bielsnohr regarding your comment about this pull. I do agree that this is a lots of rework and it will probably break the code of a lot of people if we merge this, since the usage is a bit different.

I would suggest that we reject this and me and whoever is willing to, make this code compliant to the current usage of scholarly.

By compliant I mean, instead of having to create a new object with options and everything I think it would be a better idea to just do "import scholarly" and perform the requests. Then we would have to decide on how to set the options (selenium, proxy, etc).

Another option is to change scholarly usage pattern to something similar to what flask does. This would mean that the user would create an object and perform calls using that object, pretty much like this is currently doing.

**Comment by bielsnohr** [comment]
@silvavn yes I think those are the two options. Put another way, do we want this pull request to evolve into a minor release (i.e. comply with existing API) or into a major release (i.e. fine to break API). I am open to both but would need to dive into the new usage of your fork to assess whether an API shift is worthwhile.

**Comment by ipeirotis** [comment]
Agree with @bielsnohr  and @silvavn that the code is a major refactor and API-breaking. Therefore, I am inclined to work first on incorporating other pull requests, and fix as many of the existing issues as possible before working on this. I would treat this as a major release, but still, try to minimize API changes.

**Comment by liujiajun** [comment]
@silvavn May I know on which platform did you tested this PR?

I tried it on my Mac, and it is not usable. i.e. A lot of errors, bugs, and inconsistencies. 

For example, `Author.py` still sticks to the old constants like `_CITATIONAUTHRE`, which should have been replaced by `self._scholarly.URLS('CITATIONAUTHRE')` according to your implementation.

Is it I am doing it wrong or the PR is still work-in-progess?

**Comment by silvavn** [comment]
@liujiajun I tested on windows.
I am closing this pull request so we can work on a break down of this pull request.

**Pull request closed without merging**
